services:
  # Backend only - serve API
  - type: web
    name: flowsync-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Tharika:tharika13@cluster0.j0wvduu.mongodb.net/project_management?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    plan: free
