services:
  - type: web
    name: flowsync-app
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm run start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Tharika:tharika13@cluster0.j0wvduu.mongodb.net/project_management?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    plan: free
    disk:
      name: public
      mountPath: /app/backend/public
      sizeGB: 1
